iosched: IOoperation.h Scheduler.h main.cpp FIFOScheduler.cpp SSTFScheduler.cpp LOOKScheduler.cpp CLOOKScheduler.cpp FLOOKScheduler.cpp
	g++ main.cpp FIFOScheduler.cpp SSTFScheduler.cpp LOOKScheduler.cpp CLOOKScheduler.cpp FLOOKScheduler.cpp -o iosched
clean:
	rm iosched
