p: PTE.h Frame.h Pager.h Process.h main.cpp Process.cpp \
	PagerFIFO.cpp PagerRandom.cpp PagerClock.cpp PagerNRU.cpp PagerAging.cpp PagerWorkingSet.cpp
	g++ main.cpp Process.cpp PagerFIFO.cpp PagerRandom.cpp PagerClock.cpp PagerNRU.cpp \
		PagerAging.cpp PagerWorkingSet.cpp -o p
clean:
	rm p
